language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "VZLLuza/RSJCKp/4Y+SvzUGUPz/KWI6XezaIG0PZ9l/MeyHzjHSt0/53NHZZMRJsMjrc4Htj/CswOHLKOi1Fv5/IkTSj4HKvrHmYdy8nZmv3J/xAmCMBv8RK/GXSfDoeg3B7XwR009mI8zJ+BzmVmUs1dr6hsClnmB3H7a9G81Zf9E/5x+pdWaTo5iMsBNK26Q9y0LTd2DHj1w9IaZOBVKw44E8EhUykWOUbl+5pn5RRE6fSwBSE4IwCoTopeHCOD4QvM11mEAV1A2c31e74OmpH0z5EZ/K9FeCcJJ1n2lLx2DybCRdz8GFfDbxjl24co2BTSsmlNqKGqjnguCiQSktqyCCQLeGHOcjcstlDJ4ZNGapIc6E6ITdxRZLyrUu1wlyrnLXUFnsHmUBmmEIRwBFhWp/a93nEQFig6vOzS4ykgO/1xLimXm7wEaB/a11C1dSH1hJdo78S3Gm15G/BnfPmw+x1MCP7QuyzJQndCJ60imTF9XfGWqEny/kjgmz42aoPaksYNxRU2Ue7ct8LzrFzHoM4+IC/PJgthAwqX4CtU1Om1fY3pzLL7dX6zyEBsTncpit+1P5RaZ6q+YOlCegG2cyitaj5zb8ZAOrRrK/70KK89dP6fDXPj+xITRck+OiFRNhSfCx3kcVjSPVAznVM30MMLhmMaay0PbFJd+A="
    on:
      branch: master
