language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "iSCptu6ClGsq1mmmKuuK6l1zhSIy2kI8OLOtyPZUz8OpzJ87WsXAAEaXLay9ksFpqQDaSYurtSj2CDqHMEezMPnkZHxL1mAbkJDZQEjzzL5fHFil/m9qiitjU6wOUu0cA8HR7WtieWuJ9Wfidv9qibOeII6DAum5axTF2oyYMwCS6wf2iV/g3bzV+ViLKsdf+Gladvdrg8iuknrpJaAtQ2qTP2Dfri8+dm8Kuj978H23uXzvcjnVGusbN0aFw9OVWeARtBpWcQeh1s+jyS4xJ3mlfWiuVUpc1+U53WculL8yonFRl8ldUiEnK3/jpejTuquELBi/dwoDRXlLT6/17MSon394xwa+mdH8iD/2EKUIFyjA7zAUg9qfnkStnGtR9LIzxykqL06Lh5OV3o+ug6yaInwkV4KuJumtQBEu7sSD2C3IAJHINHSQ+mG/7324GLdGdYtpro+p/T56o5wWuIaaY8eZ+tgJ0p08WZkL9YwjqiO1lCadh2kNITYEAa5q89BcBU5+2XZ0+u/2vV49urNkxM1yedX21YuRvI9Mfzu0Z5O2rhxQxsPPMTF4cwcNvu6eh9wdujzQX6lwvEAIlATVKgG8gu/1uEFslnA3+oT7HXosLzNElHj0rMmHJVlxZGi+9CVkKQEYE7hdul+qPJBGLurNCR06noWgaa2WPeQ="
    on:
      branch: master
